#!/bin/sh -ex

DB_NAME=sugarcrm
DB_USER=sugarcrm
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey

SRC=/usr/local/src
WEBROOT=/var/www/sugarcrm

# unpack and configure
unzip $SRC/SugarCE-*.zip -d $SRC
rm $SRC/SugarCE-*.zip
mv $SRC/SugarCE-* $WEBROOT
chown -R root:root $WEBROOT

touch $WEBROOT/install.log

chown -R www-data:www-data $WEBROOT/cache
chown -R www-data:www-data $WEBROOT/custom
chown -R www-data:www-data $WEBROOT/modules
chown -R www-data:www-data $WEBROOT/upload
chown www-data:www-data $WEBROOT/config.php
chown www-data:www-data $WEBROOT/sugarcrm.log
chown www-data:www-data $WEBROOT/install.log
chown www-data:www-data $WEBROOT/.htaccess

# php.ini tweaks
PHPINI=/etc/php5/apache2/php.ini
sed -i "s|^memory_limit.*|memory_limit = 256M|" $PHPINI
sed -i "s|^variables_order.*|variables_order = \"EGPCS\"|" $PHPINI
sed -i "s|^;date.timezone.*|date.timezone = \"UTC\"|" $PHPINI

